-- =============================================
-- TalentCRM - Supabase SQL Schema
-- =============================================
-- Run this SQL in your Supabase SQL Editor
-- Go to: https://supabase.com/dashboard > Your Project > SQL Editor
-- =============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- 1. PROFILES TABLE (linked to auth.users)
-- =============================================
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
        email TEXT,
            name TEXT,
                role TEXT DEFAULT 'employee' CHECK (role IN ('admin', 'employee')),
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                        updated_at TIMESTAMPTZ DEFAULT NOW()
                        );

                        -- Enable RLS
                        ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

                        -- Profiles Policies
                        CREATE POLICY "Users can view all profiles" ON profiles
                            FOR SELECT USING (true);

                            CREATE POLICY "Users can update own profile" ON profiles
                                FOR UPDATE USING (auth.uid() = id);

                                CREATE POLICY "Admins can update any profile" ON profiles
                                    FOR UPDATE USING (
                                            EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
                                                );

                                                CREATE POLICY "Service role can insert profiles" ON profiles
                                                    FOR INSERT WITH CHECK (true);

                                                    -- Trigger to create profile on user signup
                                                    CREATE OR REPLACE FUNCTION public.handle_new_user()
                                                    RETURNS TRIGGER AS $$
                                                    BEGIN
                                                        INSERT INTO public.profiles (id, email, name, role)
                                                            VALUES (
                                                                    NEW.id,
                                                                            NEW.email,
                                                                                    COALESCE(NEW.raw_user_meta_data->>'name', NEW.email),
                                                                                            COALESCE(NEW.raw_user_meta_data->>'role', 'employee')
                                                                                                );
                                                                                                    RETURN NEW;
                                                                                                    END;
                                                                                                    $$ LANGUAGE plpgsql SECURITY DEFINER;

                                                                                                    -- Drop trigger if exists and recreate
                                                                                                    DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
                                                                                                    CREATE TRIGGER on_auth_user_created
                                                                                                        AFTER INSERT ON auth.users
                                                                                                            FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

                                                                                                            -- =============================================
                                                                                                            -- 2. CLIENTS TABLE (CRM)
                                                                                                            -- =============================================
                                                                                                            CREATE TABLE IF NOT EXISTS clients (
                                                                                                                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                    company_name TEXT NOT NULL,
                                                                                                                        contact_name TEXT,
                                                                                                                            email TEXT,
                                                                                                                                phone TEXT,
                                                                                                                                    status TEXT DEFAULT 'prospect' CHECK (status IN ('active', 'prospect', 'inactive', 'negotiation')),
                                                                                                                                        revenue DECIMAL(15, 2) DEFAULT 0,
                                                                                                                                            notes TEXT,
                                                                                                                                                assigned_to UUID REFERENCES profiles(id),
                                                                                                                                                    created_at TIMESTAMPTZ DEFAULT NOW(),
                                                                                                                                                        updated_at TIMESTAMPTZ DEFAULT NOW()
                                                                                                                                                        );

                                                                                                                                                        -- Enable RLS
                                                                                                                                                        ALTER TABLE clients ENABLE ROW LEVEL SECURITY;

                                                                                                                                                        -- Clients Policies
                                                                                                                                                        CREATE POLICY "Users can view all clients" ON clients
                                                                                                                                                            FOR SELECT USING (true);

                                                                                                                                                            CREATE POLICY "Users can insert clients" ON clients
                                                                                                                                                                FOR INSERT WITH CHECK (true);

                                                                                                                                                                CREATE POLICY "Users can update clients" ON clients
                                                                                                                                                                    FOR UPDATE USING (true);

                                                                                                                                                                    CREATE POLICY "Only admins can delete clients" ON clients
                                                                                                                                                                        FOR DELETE USING (
                                                                                                                                                                                EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
                                                                                                                                                                                    );

                                                                                                                                                                                    -- =============================================
                                                                                                                                                                                    -- 3. TRAINERS TABLE (FORMATEURS)
                                                                                                                                                                                    -- =============================================
                                                                                                                                                                                    CREATE TABLE IF NOT EXISTS trainers (
                                                                                                                                                                                        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                                                                                            first_name TEXT NOT NULL,
                                                                                                                                                                                                last_name TEXT NOT NULL,
                                                                                                                                                                                                    email TEXT,
                                                                                                                                                                                                        phone TEXT,
                                                                                                                                                                                                            diploma_level TEXT DEFAULT 'bac+5',
                                                                                                                                                                                                                expertise TEXT[] DEFAULT '{}',
                                                                                                                                                                                                                    schools TEXT,
                                                                                                                                                                                                                        comments TEXT,
                                                                                                                                                                                                                            created_at TIMESTAMPTZ DEFAULT NOW(),
                                                                                                                                                                                                                                updated_at TIMESTAMPTZ DEFAULT NOW()
                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                -- Enable RLS
                                                                                                                                                                                                                                ALTER TABLE trainers ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                -- Trainers Policies
                                                                                                                                                                                                                                CREATE POLICY "Users can view all trainers" ON trainers
                                                                                                                                                                                                                                    FOR SELECT USING (true);

                                                                                                                                                                                                                                    CREATE POLICY "Users can insert trainers" ON trainers
                                                                                                                                                                                                                                        FOR INSERT WITH CHECK (true);

                                                                                                                                                                                                                                        CREATE POLICY "Users can update trainers" ON trainers
                                                                                                                                                                                                                                            FOR UPDATE USING (true);

                                                                                                                                                                                                                                            CREATE POLICY "Only admins can delete trainers" ON trainers
                                                                                                                                                                                                                                                FOR DELETE USING (
                                                                                                                                                                                                                                                        EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                            -- 4. TALENTS TABLE (JEUNES POTENTIELS)
                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                            CREATE TABLE IF NOT EXISTS talents (
                                                                                                                                                                                                                                                                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                                                                                                                                                                    first_name TEXT NOT NULL,
                                                                                                                                                                                                                                                                        last_name TEXT NOT NULL,
                                                                                                                                                                                                                                                                            email TEXT,
                                                                                                                                                                                                                                                                                phone TEXT,
                                                                                                                                                                                                                                                                                    birth_date DATE,
                                                                                                                                                                                                                                                                                        status TEXT DEFAULT 'active' CHECK (status IN ('active', 'follow_up', 'inactive', 'high_potential')),
                                                                                                                                                                                                                                                                                            interests TEXT,
                                                                                                                                                                                                                                                                                                aspirations TEXT,
                                                                                                                                                                                                                                                                                                    expertise TEXT[] DEFAULT '{}',
                                                                                                                                                                                                                                                                                                        assigned_to UUID REFERENCES profiles(id),
                                                                                                                                                                                                                                                                                                            created_at TIMESTAMPTZ DEFAULT NOW(),
                                                                                                                                                                                                                                                                                                                updated_at TIMESTAMPTZ DEFAULT NOW()
                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                -- Enable RLS
                                                                                                                                                                                                                                                                                                                ALTER TABLE talents ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                -- Talents Policies
                                                                                                                                                                                                                                                                                                                CREATE POLICY "Users can view all talents" ON talents
                                                                                                                                                                                                                                                                                                                    FOR SELECT USING (true);

                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can insert talents" ON talents
                                                                                                                                                                                                                                                                                                                        FOR INSERT WITH CHECK (true);

                                                                                                                                                                                                                                                                                                                        CREATE POLICY "Admins can update any talent" ON talents
                                                                                                                                                                                                                                                                                                                            FOR UPDATE USING (
                                                                                                                                                                                                                                                                                                                                    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                        CREATE POLICY "Employees can update assigned talents" ON talents
                                                                                                                                                                                                                                                                                                                                            FOR UPDATE USING (
                                                                                                                                                                                                                                                                                                                                                    assigned_to = auth.uid() OR
                                                                                                                                                                                                                                                                                                                                                            EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                CREATE POLICY "Only admins can delete talents" ON talents
                                                                                                                                                                                                                                                                                                                                                                    FOR DELETE USING (
                                                                                                                                                                                                                                                                                                                                                                            EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                -- 5. EXPERTISE CATEGORIES TABLE
                                                                                                                                                                                                                                                                                                                                                                                -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                CREATE TABLE IF NOT EXISTS expertise_categories (
                                                                                                                                                                                                                                                                                                                                                                                    id TEXT PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                        name TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                            subcategories TEXT[] DEFAULT '{}',
                                                                                                                                                                                                                                                                                                                                                                                                created_at TIMESTAMPTZ DEFAULT NOW()
                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                -- Enable RLS
                                                                                                                                                                                                                                                                                                                                                                                                ALTER TABLE expertise_categories ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                                                                                                CREATE POLICY "Everyone can view expertise categories" ON expertise_categories
                                                                                                                                                                                                                                                                                                                                                                                                    FOR SELECT USING (true);

                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Only admins can modify expertise categories" ON expertise_categories
                                                                                                                                                                                                                                                                                                                                                                                                        FOR ALL USING (
                                                                                                                                                                                                                                                                                                                                                                                                                EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Insert default expertise categories
                                                                                                                                                                                                                                                                                                                                                                                                                    INSERT INTO expertise_categories (id, name, subcategories) VALUES
                                                                                                                                                                                                                                                                                                                                                                                                                        ('cultural', 'Industries Culturelles & Créatives', ARRAY['Musique', 'Arts', 'Design', 'Médias', 'Diversité']),
                                                                                                                                                                                                                                                                                                                                                                                                                            ('sport', 'Sport & Performance Durable', ARRAY['Innovation', 'Santé', 'Inclusion', 'Bien-être']),
                                                                                                                                                                                                                                                                                                                                                                                                                                ('industry', 'Industrie du Futur', ARRAY['Industrie résiliente', 'Économie circulaire', 'Production intelligente']),
                                                                                                                                                                                                                                                                                                                                                                                                                                    ('resources', 'Gestion des Ressources', ARRAY['Eau', 'Énergie', 'Biodiversité', 'Anti-gaspillage']),
                                                                                                                                                                                                                                                                                                                                                                                                                                        ('luxury', 'Luxe & Tourisme Responsable', ARRAY['Luxe durable', 'Tourisme éthique']),
                                                                                                                                                                                                                                                                                                                                                                                                                                            ('agritech', 'AgriTech', ARRAY['Agriculture connectée', 'Souveraineté alimentaire'])
                                                                                                                                                                                                                                                                                                                                                                                                                                            ON CONFLICT (id) DO NOTHING;

                                                                                                                                                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                            -- 6. DOCUMENTS TABLE
                                                                                                                                                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE TABLE IF NOT EXISTS documents (
                                                                                                                                                                                                                                                                                                                                                                                                                                                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                    entity_type TEXT NOT NULL CHECK (entity_type IN ('trainer', 'talent', 'client', 'general')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        entity_id UUID,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            file_name TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                file_path TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    file_type TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        file_size BIGINT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            uploaded_by UUID REFERENCES profiles(id),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                created_at TIMESTAMPTZ DEFAULT NOW()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- Enable RLS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ALTER TABLE documents ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CREATE POLICY "Users can view all documents" ON documents
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FOR SELECT USING (true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can upload documents" ON documents
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FOR INSERT WITH CHECK (true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CREATE POLICY "Only admins can delete documents" ON documents
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FOR DELETE USING (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- 7. ACTIVITIES TABLE (Timeline)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CREATE TABLE IF NOT EXISTS activities (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                entity_type TEXT NOT NULL CHECK (entity_type IN ('client', 'trainer', 'talent')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    entity_id UUID NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        activity_type TEXT DEFAULT 'note',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            description TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                performed_by UUID REFERENCES profiles(id),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    created_at TIMESTAMPTZ DEFAULT NOW()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -- Enable RLS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE activities ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can view all activities" ON activities
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FOR SELECT USING (true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CREATE POLICY "Users can create activities" ON activities
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FOR INSERT WITH CHECK (true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- 8. RECOMMENDATIONS TABLE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE TABLE IF NOT EXISTS recommendations (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type TEXT NOT NULL CHECK (type IN ('follow_up', 'missing_info', 'match', 'engagement')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            description TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                entity_type TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    entity_id UUID,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        priority INTEGER DEFAULT 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            is_read BOOLEAN DEFAULT FALSE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                created_at TIMESTAMPTZ DEFAULT NOW()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                -- Enable RLS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ALTER TABLE recommendations ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CREATE POLICY "Users can view recommendations" ON recommendations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FOR SELECT USING (true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "System can create recommendations" ON recommendations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FOR INSERT WITH CHECK (true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CREATE POLICY "Users can update recommendations" ON recommendations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FOR UPDATE USING (true);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- 9. STORAGE BUCKET
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- Create storage bucket for documents
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- Run this in SQL or create via Supabase Dashboard > Storage
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            INSERT INTO storage.buckets (id, name, public)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            VALUES ('documents', 'documents', false)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ON CONFLICT (id) DO NOTHING;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- Storage Policies
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE POLICY "Users can upload documents" ON storage.objects
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FOR INSERT WITH CHECK (bucket_id = 'documents');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CREATE POLICY "Users can view documents" ON storage.objects
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    FOR SELECT USING (bucket_id = 'documents');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Admins can delete documents" ON storage.objects
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        FOR DELETE USING (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bucket_id = 'documents' AND
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- INDEXES for better performance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_clients_status ON clients(status);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_clients_assigned_to ON clients(assigned_to);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_trainers_expertise ON trainers USING GIN(expertise);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_talents_status ON talents(status);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_talents_assigned_to ON talents(assigned_to);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_talents_expertise ON talents USING GIN(expertise);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_documents_entity ON documents(entity_type, entity_id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_activities_entity ON activities(entity_type, entity_id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CREATE INDEX IF NOT EXISTS idx_recommendations_type ON recommendations(type);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- DONE!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- After running this SQL:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- 1. Enable Google OAuth in Supabase Dashboard > Authentication > Providers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- 2. Add your redirect URLs in Supabase Dashboard > Authentication > URL Configuration
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -- 3. Create your first admin user and manually update their role to 'admin' in the profiles table
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            